export { default as Login } from "./Login"
export { default as Registrar } from "./Registrar"
export { default as OlvidePassword } from "./OlvidePassword"
export { default as ConfirmarCuenta } from "./ConfirmarCuenta"
export { default as NuevoPassword } from "./NuevoPassword"
export { default as AdministrarPaciente } from "./AdministrarPaciente"